### ISSUE TITLE
Bug - Post-install AMI not movable to other instances

### ISSUE THREAD

**Issue by j99ca** [open-edge-platform/geti_v2#915]
### 🧩 Issue type

Bug 🐞

### 📄 Description

In Geti 2.11, currently creating an AMI post-install and booting up new instances (with different public/private IP addresses) seems to cause issues. After booting the new instance with the AMI created on the previous, when attempting to login this error message is displayed:

<img width="653" height="720" alt="Image" src="https://github.com/user-attachments/assets/949a84b5-9289-4318-84b1-b85da599d7a3" />

### 📋 Steps to reproduce (if applicable)

1. In EC2 Create a new instance and [install Geti as per the documentation](https://docs.geti.intel.com/docs/user-guide/getting-started/installation/cloud-installation/aws)
2. Shutdown the instance
3. Take an AMI snapshot of the instance
4. Startup a new instance using the AMI
5. Try to login to the new instance

Post login shows an error screen

### 💻 Expected behavior

Geti should not get into a weird state when booted up from a different public/private IP address

### 🖼️ Screenshots, video recordings or logs

Image of the error message post-login:

<img width="653" height="720" alt="Image" src="https://github.com/user-attachments/assets/c019df34-662f-4634-a5fc-8940a45a0aed" />

### 📦 Geti version

2.11

### 🖥️ Operating System

Ubuntu 24.04

**Comment by mgumowsk** [comment]
Hi @j99ca,
when creating the instance from AMI, the new internal IP address is assigned and a new k3s node created. Please try to remove previous node by running this command on instance created from AMI:

`
sudo kubectl delete node $(sudo kubectl get nodes | grep NotReady | awk '{print $1;}')
`
and then label the new node as GPU supported:
`
sudo kubectl label node $(sudo kubectl get nodes | grep Ready | awk '{print $1;}') nvidia.com/gpu=true
`

Then wait a few minutes and please try to login again.

**Comment by j99ca** [comment]
@mgumowsk I have followed thyose instructions, and I am still getting a technical difficulties page when I login:

<img width="671" height="743" alt="Image" src="https://github.com/user-attachments/assets/4ed45f26-e552-406a-b2d8-bc4d69493d06" />

Steps taken:

1) Initial AWS instance Geti install using https://docs.geti.intel.com/docs/user-guide/getting-started/installation/cloud-installation/aws
2) shutdown the instance
3) snapshot made of the instance
4) started up a new instance with the snapshot
5) attempt to login with the admin credentials made from step 1

The original instance is working, but the new one booted from the AMI does not. I am on Geti 2.11

**Comment by mgumowsk** [comment]
Can you provide a list of nodes and pods status? 
sudo kubectl get nodes
sudo kubectl get pods --all-namespaces

**Comment by piotrgrubicki** [comment]
@j99ca , is this issue still valid?

**Comment by piotrgrubicki** [comment]
@j99ca , I assume this problem has been solved. Closing the ticket.

**Comment by piotrgrubicki** [comment]
@j99ca , with respect to our email exchange, I am reopening this issue and waiting for you response when you will have a chance to revisit this issue again.

**Comment by piotrgrubicki** [comment]
@j99ca , have you had a chance to revisit this issue?

**Comment by j99ca** [comment]
@piotrgrubicki I am going to test this today or tomorrow, I was on vacation and am just getting caught up on some tasks

**Comment by j99ca** [comment]
@piotrgrubicki I can confirm that this still appears to be an issue.

Steps taken:

1. Followed the instructions from here, though I chose to do the "Manual configuration of EC2" section rather than the User data script.
2. OS was Ubuntu 24.04, instance g4dn.4xlarge, 500GB of storage.
3. During the installation, it seemed stuck on 86% for a couple of hours, though eventually my SSH session timed out so I am not sure if it actually reached 100%. However, I was able to connect and log into this instance's Geti account via the web interface, and everything seems to be working fine?
4. I ran the terminal commands listed at the bottom of cloud-installation/aws
5. I shutdown the instance.
6. I created an AMI through EC2 in Actions -> Image and templates -> Create image
7. I booted a new EC2 instance from this AMI
8. When I try to log into Geti on this new instance which was booted from the AMI snapshot, I get the error message

``
We are experiencing technical difficulties
We apologize for the inconvenience, but we are currently experiencing technical difficulties. Our team is actively working to resolve the issue and restore full functionality as quickly as possible.
If you require immediate assistance or have any urgent concerns, please do not hesitate to reach out to ourcustomer support team.
``

<img width="1912" height="929" alt="Image" src="https://github.com/user-attachments/assets/ce207f3d-0127-4ee8-89ec-6826fff51c18" />


Additional notes:
The link from the page cloud-installation/aws in the text "Being connected via SSH, you can proceed with the actual Geti™ installation following Using Geti™ Installer" is broken.

**Comment by mgumowsk** [comment]
I got the logs from @j99ca
```ubuntu@ip-172-31-38-63:~$  sudo kubectl get nodes
NAME              STATUS     ROLES                  AGE   VERSION
ip-172-31-38-63   Ready      control-plane,master   18d   v1.31.0+k3s1
ip-172-31-45-88   NotReady   control-plane,master   19d   v1.31.0+k3s1
```
I suggested to delete NotReady node with `sudo kubectl delete node ip-172-31-45-88`

**Comment by piotrgrubicki** [comment]
@j99ca ,
To summarize, the root cause of this issue is related to the different host name that is assigned to new EC2 instances and Geti installer that does not enforce a particular Kubernetes node name. In such a scenario, Kubernetes takes a host name as its node name, which causes problems when starting a new EC2 from an AMI (duplicated nodes mentioned above).
In future versions, we can enforce this node name to remedy the situation.
In the meantime, I confirmed that the following solution will work for you. Do follow, please, the steps [here](https://docs.geti.intel.com/docs/user-guide/getting-started/installation/using-helm-charts) to install Geti via Helm charts. With one change to enforce the node name. Instead of [the command mentioned there to install K3s](https://docs.geti.intel.com/docs/user-guide/getting-started/installation/using-helm-charts#k3s-installation-optional), use:
```
curl -sfL https://get.k3s.io | \
  INSTALL_K3S_VERSION=v1.31.0+k3s1 \
  INSTALL_K3S_EXEC="--disable traefik \
      --node-name geti \
      --default-runtime nvidia \
      --service-node-port-range 30000-30050 \
      --kube-apiserver-arg=enable-admission-plugins=NodeRestriction,ServiceAccount \
      --kube-apiserver-arg=request-timeout=5m0s \
      --kube-apiserver-arg=audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log \
      --kube-apiserver-arg=tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 \
      --kube-apiserver-arg=audit-log-maxbackup=10 \
      --kube-apiserver-arg=event-ttl=72h \
      --kube-controller-manager-arg=terminated-pod-gc-threshold=1000 \
      --kube-controller-manager-arg=leader-elect-lease-duration=30s \
      --kube-controller-manager-arg=leader-elect-renew-deadline=20s \
      --kube-controller-manager-arg=bind-address=127.0.0.1 \
      --kube-scheduler-arg=bind-address=127.0.0.1 \
      --kubelet-arg=streaming-connection-idle-timeout=5m \
      --kubelet-arg=rotate-server-certificates=true \
      --kubelet-arg=eviction-hard=imagefs.available<5Gi,memory.available<100Mi,nodefs.available<5Gi,nodefs.inodesFree<5% \
      --kubelet-arg=eviction-minimum-reclaim=imagefs.available=1Gi,nodefs.available=1Gi \
      --kubelet-arg=image-gc-low-threshold=0" \
  sh -s -
```
After installing Geti this way, you can create the AMI image and use it to set up EC2 instances without any additional steps.

**Comment by piotrgrubicki** [comment]
@j99ca , you can take the newest 2.13.1 and create instances from AMI (with Geti 2.13.1) without any workarounds.

**Comment by j99ca** [comment]
@piotrgrubicki I can confirm that 2.13.1 seems to have resolved the problem! I was able to create an AMI from an instance running Geti 2.13.1, create a snapshot AMI, then boot a fresh instance from that snapshot and login in successfully!
